[phases.setup]
cmds = [
    # Backend
    "cd backend && composer install --no-dev",
    # Frontend (se usar build)
    "cd frontend && npm install"
]

[phases.build]
cmds = [
    # Se seu frontend precisa de build (React/Vue/etc)
    "cd frontend && npm run build",
    # Copia frontend para a pasta pública (opcional)
    "cp -r frontend/* backend/public/"
]

[phases.start]
cmd = "cd backend && php -S 0.0.0.0:$PORT -t public"

[vars]
NIXPACKS_PHP_ROOT_DIR = "/app/backend/public"