[phases.setup]
cmds = [
    "cd backend && composer install --no-dev",
    "cd frontend && npm install"
]

[phases.build]
cmds = [
    "cd frontend && npm run build",
    "mkdir -p backend/public",
    "cp -r frontend/dist/* backend/public/ || true"
]

[phases.start]
cmd = "cd backend && php -S 0.0.0.0:$PORT -t public"

[vars]
NIXPACKS_PHP_ROOT_DIR = "/app/backend/public"
